### ISSUE TITLE
[FEATURE] Oracle driver

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [danvergara/dblab#110]
I would like to have support for oracle databases `go_ora` maybe?

**Comment by danvergara** [comment]
Yeah, why not. We recently added support for sqlite. But first, we need to do a massive refactor, to add more drivers, in fact.

**Comment by sschneider-ihre-pvs** [comment]
Greate @danvergara when will the release with oracle support be available?

**Comment by danvergara** [comment]
@sschneider-ihre-pvs [v0.24.0](https://github.com/danvergara/dblab/releases/tag/v0.24.0) is already available!!

**Comment by sschneider-ihre-pvs** [comment]
great

**Comment by sschneider-ihre-pvs** [comment]
![image](https://github.com/danvergara/dblab/assets/86342787/9f9bbf79-a5ec-4bdd-9b5d-dc858d10d002)
:(
is there a db version restriction?

**Comment by sschneider-ihre-pvs** [comment]
or windows

**Comment by sschneider-ihre-pvs** [comment]
> @sschneider-ihre-pvs I think it has to do with the syntax of your query. Is your query using JOINs or ending with semicolons. I got the same error because I wasn't aware of the changes of the Oracle syntax.

I tried to select a table to see the data
so ctrl+h navigate to table and hitting enter

**Comment by danvergara** [comment]
This is the container image I use for testing:

![Screenshot from 2024-06-06 11-43-18](https://github.com/danvergara/dblab/assets/12239167/4738b80d-4961-46d1-bdd1-b0024c7969b0)

**Comment by sschneider-ihre-pvs** [comment]
Ah yes, I have an older db that does not support things like TAKE FETCH NEXT OFFSET and so on, so that would explain it.
So I guess you need at least v12c
