### ISSUE TITLE
"go-sqlite3 requires cgo to work. This is a stub"

### ISSUE THREAD

**Issue by gravityFlower** [danvergara/dblab#111]
**Describe the bug**
dblab does not start on Windows given an sqlite db. It fails with error message `Error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`

**To Reproduce**
1. Download dblab_0.16.0_windows_amd64.tar.gz 
2. Extract
3. Open `Windows-Terminal` app in extracted Folder
4. Try to open an sqlite db by running `.\dblab.exe --driver sqlite3 --db "P:\ath\To\sqlite.db"`

**Expected behavior**
dblab opens

**OS (please complete the following information):**
 - Microsoft Windows 10 Pro x64 Version 10.0.19044 Build 19044

**Comment by danvergara** [comment]
That's on me. The tar file contains two files: dblab (the regular binary) and dblab-sqlite (with cgo enabled), but I forgot to mention that on the documentation. Please, use the latter. It should work, otherwise let me know in this thread.

**Comment by gravityFlower** [comment]
Doesn't seem to work for me. Both executables give me the same error.
![grafik](https://user-images.githubusercontent.com/12392087/191853485-2ebf62eb-e1e5-4107-b897-ca00ffd8a7e5.png)

**Comment by danvergara** [comment]
Are you sure? Just tested out both binaries and just the regular one fails when I try to open a sqlite database. @israteneda you work with Windows systems right? Can you confirm?

**Comment by jacklocke** [comment]
Same on Ubuntu and a SQLite database

**Comment by danvergara** [comment]
![Screenshot from 2022-09-23 10-41-07](https://user-images.githubusercontent.com/12239167/192000091-2da08d16-4e6e-4dcf-9812-43233cb2ba64.png)

Seriously guys, still don't what's going on in your systems.

**Comment by danvergara** [comment]
I'm going to spend the rest of the day tracing down the compiling error, maybe it has to do with the goreleaser's cross-compiling limitations.

**Comment by gravityFlower** [comment]
Just as a note: can confirm the linux version works as expected, tested on wsl/ubuntu 20.04
To confirm it wasn't a local machine error, i set up a virtual machine with a windows 10 iso, downloaded release v0.16.0, ran dblab-sqlite and got the same error.

**Comment by danvergara** [comment]
accidentally closed the issue. Thanks a lot @gravityFlower for going through this. I still tracing down the error. Pretty sure it has to with goreleases. Will setup a better test environment for Windows for the upcoming releases.

**Comment by jacklocke** [comment]
> ![Screenshot from 2022-09-23 10-41-07](https://user-images.githubusercontent.com/12239167/192000091-2da08d16-4e6e-4dcf-9812-43233cb2ba64.png)
> 
> Seriously guys, still don't what's going on in your systems.

./dblab-sqlite works for me on another system

**Comment by danvergara** [comment]
I dropped a new [PR](https://github.com/danvergara/dblab/pull/114) to fix this as I promised a few days ago. Please take a look and feel free to leave a comment if you spot anything wrong.

cc @gravityFlower @jacklocke @israteneda

**Comment by danvergara** [comment]
We're making progress! I was able to run a binary compiled through gorelleaser cli, locally. Obviously installing the correspondent cross-compilation tools for windows. Now, we're in a position to ship a candidate release.

![Screenshot from 2022-09-28 19-25-52](https://user-images.githubusercontent.com/12239167/192911754-44c9304e-5314-4ae0-9b43-0074f6ef7508.png)

**Comment by danvergara** [comment]
@gravityFlower I've released a rc for v0.16.1. Care to test it out for us?

https://github.com/danvergara/dblab/releases/tag/untagged-663792a1cf9ae3c9e192

**Comment by danvergara** [comment]
Finally we have a working release candidate for this. Please, check it out.

https://github.com/danvergara/dblab/releases/tag/v0.16.1-rc1
cc. @gravityFlower @jacklocke @israteneda

**Comment by gravityFlower** [comment]
The version v0.16.1 of dblab-sqlite doesn't complain anymore and i am able to open an sqlite db under windows 10.
