### ISSUE TITLE
Redraw UI on terminal resize

### ISSUE THREAD

**Issue by guyfedwards** [danvergara/dblab#123]
**Describe the bug** 

Currently resizing the terminal does not redraw the UI leaving it the wrong size and data hidden.

**To Reproduce**
1. Launch dblab
2. Resize terminal

**Expected behavior**
The UI to redraw to the new terminal size.

**Screenshots**
![2022-10-03_230336](https://user-images.githubusercontent.com/1794071/193694355-ca0f6037-c297-421c-9146-8585d3571f85.jpg)

**OS (please complete the following information):**
- Linux archlinux 5.19.3-arch1-1 x86_64 GNU/Linux
- alacritty terminal
- tmux

**Additional context**

**Comment by danvergara** [comment]
Thank you for bringing this to my attention. Actually, it's already on top of my list of priorities. Since I fixed a bunch of critical bugs, I have the bandwidth to tackle that issue now. If you don't mind, I'm going to use this issue to report ongoing progress.

**Comment by danvergara** [comment]
@guyfedwards I came up with a bugfix in #124. Please, check it out! If this solves the problem, the change is gonna make it to the next Patch release v0.16.2.

**Comment by guyfedwards** [comment]
Thanks @danvergara

**Comment by danvergara** [comment]
@guyfedwards the bugfix is finally available as of [v0.16.2](https://github.com/danvergara/dblab/releases/tag/v0.16.2)
