### ISSUE TITLE
[FEATURE] Add query completion and syntax highlighting

### ISSUE THREAD

**Issue by Crandel** [danvergara/dblab#142]
**Describe the solution you'd like**
It would be a good feature to complete via TAB SQL words and table names, columns, etc. while typing SQL queries in SQL Query panel   

**Describe alternatives you've considered**
There is a cli tool [usql](https://github.com/xo/usql) written in Go with syntax highlighting and code completion. You could check how this feature is implemented there.

**Comment by danvergara** [comment]
Nice suggestion!! It's a good idea, but a bit complex since the TUI library is the responsible to provide the editor. So, I have to figure out a way to leverage it. Fortunately, I forked that library, so I can implement something to extend the current editor's functionalities.

**Comment by Crandel** [comment]
Awesome! Thank you for quick response

**Comment by rkgarcia** [comment]
[usql](https://github.com/xo/usql) looks pretty cool!

**Comment by danvergara** [comment]
@rkgarcia  The problem is that we need to embed the tool into the text editor and I hesitated to complete this because I'm planning to ditch the current TUI library in favor of Charm
