### ISSUE TITLE
[FEATURE] Add SSL flags usage for PostgreSQL to the docs

### ISSUE THREAD

**Issue by valerybriz** [danvergara/dblab#175]
**Is your feature request related to a problem? Please describe.**
Add the documentation for the SSL flags usage for PostgreSQL

**Describe the solution you'd like**
Clearly explain the usage of the SSL flags and add it to the usage file in the documentation.

**Describe alternatives you've considered**
If possible also add an example of this into the tutorials section.

**Comment by danvergara** [comment]
Clossing this issue, since this was introduced in [v0.21.0](https://github.com/danvergara/dblab/releases/tag/v0.21.0)
