### ISSUE TITLE
Error using sqlite without parameters 

### ISSUE THREAD

**Issue by rkgarcia** [danvergara/dblab#176]
**Describe the bug**
When I run the command and select sqlite, I received an error "Error: strconv.Atoi: parsing "": invalid syntax"

**To Reproduce**
1. Run command dblab
2. Select sqlite driver
3. Fill file path with relative path to existent (or unexistent) file path, press enter
4. Left the limit empty and press enter
5. Press enter for ssl too

**Expected behavior**
Connect to database

**Screenshots**

**OS (please complete the following information):**
 - Windows 11

**Additional context**
Using Windows Command Prompt.

**Comment by danvergara** [comment]
Closing this since this was patched in [v0.21.0](https://github.com/danvergara/dblab/releases/tag/v0.21.0)
