### ISSUE TITLE
[FEATURE] Microsoft SQL Server driver

### ISSUE THREAD

**Issue by selfagency** [danvergara/dblab#188]
Request in title.

**Comment by tracker1** [comment]
https://github.com/denisenkom/go-mssqldb

**Comment by emisjerry** [comment]
+1

**Comment by danvergara** [comment]
@selfagency @tracker1 and @emisjerry #222 adding sql server just dropped.
Care to test it out please.

**Comment by selfagency** [comment]
@danvergara will do, monday morning at work

**Comment by danvergara** [comment]
@selfagency the PR got merged but you can still test the new driver out and let me know if you find something wrong. Thanks!
