### ISSUE TITLE
[FEATURE] Look for config file in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ptman** [danvergara/dblab#194]
**Is your feature request related to a problem? Please describe.**

There is a standard place for config files. Store the config file there.

**Describe the solution you'd like**

Use https://pkg.go.dev/os#UserConfigDir or https://github.com/adrg/xdg

**Comment by danvergara** [comment]
Closing this issue because the code addressing this got merged and it's available as of [v0.23.0](https://github.com/danvergara/dblab/releases/tag/v0.23.0).
