### ISSUE TITLE
[FEATURE] Support PostgreSQL unix socket connection

### ISSUE THREAD

**Issue by ptman** [danvergara/dblab#195]
**Is your feature request related to a problem? Please describe.**
I'd like to connect to postgresql using unix socket.

**Describe the solution you'd like**
Either explicit unix socket support like for mysql or host=/run/postgresql syntax like postgres tools usually support.

**Comment by danvergara** [comment]
That makes sense @ptman. 
Thanks for bringing it to my attention!

I think this and #194 can be easily done, but are you Ok if I start working on those the next month? I'm in the middle of [something](https://github.com/danvergara/morphos) and I want to achieve some milestones before getting back to dblab, as I planned at the beginning of the year.
