### ISSUE TITLE
PageUp & PageDown keys

### ISSUE THREAD

**Issue by ironicviking** [danvergara/dblab#204]
I have a postgres database with 100s of tables. A lot of times i need to scroll towards the end of the tables to find the one i want. When in the left pane, i can move up and down using arrows or j & k , however I'm not able to use PageUp or PageDown to navigate the list of tables, just Up and Down 1 at a time. 

Basically it could work by scrolling down to next set of items, or scroll up/down # rows (configurable in config please :) ). 

Summary, please add PageUp & PageDown in both the table listing and dataset panels.

**Comment by danvergara** [comment]
There's two key bindings available to go to top and the bottom of the dataset panel: `g` and `G` respectively.

**Comment by danvergara** [comment]
@ironicviking I made a new PR including support to navigate with `pgdn` and `pgup`. Is this what you need?

**Comment by ironicviking** [comment]
Amazing! Will check now, thanks!

**Comment by danvergara** [comment]
Hi @ironicviking !

Did it work?
