### ISSUE TITLE
RSD Sqlite not accepted

### ISSUE THREAD

**Issue by matbgn** [danvergara/dblab#211]
**Describe the bug**
RSD Sqlite extension is not tolerated

```
Error: : invalid sqlite file extension
```

**To Reproduce**
```
dblab --db ~/Data.rsd --driver sqlite
```

**Expected behavior**
Accept .rsd as valid .sqlite alternative

**OS (please complete the following information):**
- Ubuntu 22.04 64bit / Linux 6.5.0-35-generic
- Version dblab : 0.24.0

**Comment by danvergara** [comment]
@matbgn I made a PR (#215) to address this issue. I removed all validation on sqlite file extensions, since it can be any, sqlite will figure out if the file is valid.

**Comment by matbgn** [comment]
I just tried your branch and it works! Thanks
