### ISSUE TITLE
What shortcut key should I use to execute a SQL query after entering it? I found that pressing the Enter key does not work.

### ISSUE THREAD

**Issue by hcymysql** [danvergara/dblab#234]
![image](https://github.com/user-attachments/assets/8c83a551-2abe-4b17-9d55-4ad6842e813c)
What shortcut key should I use to execute a SQL query after entering it? I found that pressing the Enter key does not work.

**Comment by abdelaziz-ouhammou** [comment]
It says in the documentation that you should press CTRL+ Enter to execute the query
