### ISSUE TITLE
Unable to connect to mariadb when password contains characters '@#'

### ISSUE THREAD

**Issue by ManjotS** [danvergara/dblab#36]
**Describe the bug**
Unable to connect to mariadb when password contains characters '@#'

**To Reproduce**
Connect to mariadb or mysql with a password containing '@#' e.g. 

./dblab --driver mysql --host xyz.abc.db.skysql.net --user myuser --pass 5@klkbN#ABC--ssl enable --port 5001

or

./dblab --driver mysql --host xyz.abc.db.skysql.net --user myuser --pass '5@klkbN#ABC'--ssl enable --port 5001

Receive this error:
Error: Error 1045: Access denied for user 'redacted'@'redactedip' (using password: YES)

**Expected behavior**
Connects

**Screenshots**

**OS (please complete the following information):**
 - MacOS BigSur 11.2.3

**Comment by danvergara** [comment]
Hi @ManjotS. Sorry for the delayed response. I tried to reproduce the error you get, but I'm gettting another error using a similar set of flags. With the set flags provided, you should get another type of error:

```
 Error: Error 1046: No database selected
```

Looks like you're having a problem related to the permissions set on your database.  Can you add the database flag `--db`, please and see what happens?

**Comment by danvergara** [comment]
I created and defined a table in a mysql docker container I was able to open a connection setting the provided credentials (myuser and 5@klkbN#ABC'). I ran out of ideas, if you have more information, don't hesitate to drop it in this discussion.

**Comment by danvergara** [comment]
I'm clossing this because of the lack of response. If he problem persists, feel free to open a new issue.
