### ISSUE TITLE
[FEATURE] It might be a good idea to add a CONTRIBUTION file and a CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by israteneda** [danvergara/dblab#38]
**Is your feature request related to a problem? Please describe.**
I'd like to contribute with the code of `dblab`, but I don't know very well `golang`

**Describe the solution you'd like**
Maybe could be a good idea to add a `CONTRIBUTING` file for new contributors to get some context of the project and for the environment setup, also could be a good idea to add a `CODE_OF_CONDUCT` to the repo, for the interaction between developers

**Describe alternatives you've considered**
I tried to run the code after I cloned, but I got an error `Error: empty values required to open a session in database`, 
I'm using `Goland`, then I noticed that I'm running the app without parameters so when I added `--help`, the error disappear

**Comment by danvergara** [comment]
Hi @israteneda. Glad you want to contribute to the project. You just discovered a dark corner of the project, what happen when you run the cli without params. I'm currently working on a solution: every time you run the project with no params, a form will be displayed asking for the right arguments.

If you would like to add contribute guidelines, that would be awesome and welcome, please do!

**Comment by israteneda** [comment]
sure thing!
I'm going to add an initial commit for the contribution guideline in the coming days.
great I'd like to see that solution, another solution could be to show the `help` message by default.
