### ISSUE TITLE
Web app to see the content on the browser

### ISSUE THREAD

**Issue by danvergara** [danvergara/dblab#77]
**Is your feature request related to a problem? Please describe.**
For some people, the terminal is a little less expressive than the desktop or web applications, so we can provide another experience to those potential users 

**Describe the solution you'd like**
My proposed solutions is to spin up a web server that serves a web application that displays the database content.

**Describe alternatives you've considered**
I've considered a GUI app, but not sure about the esthetics capabilities of the GUI frameworks.

**Comment by gedw99** [comment]
Gioui !! Golang gui :) 
Check it out . Easy to build a sql gui with it for web and desktop and mobile

**Comment by danvergara** [comment]
@gedw99 Thanks a lot! Seems promising. Since the TailScale android client is using it, I can give it a try.
