### ISSUE TITLE
Sqlite3 interactive menu prompts for host and port

### ISSUE THREAD

**Issue by israteneda** [danvergara/dblab#94]
**Describe the bug**
I was thinking that sqlite3 option should ask for the path of the SQLite file instead of host and port. What do you think?

**To Reproduce**
1. Build the app with the latest updates
2. run ./dblab
3. select sqlite3 option
4. The prompt asks for host and port

**Expected behavior**
I think the app should ask for the path of the SQLite file

**Screenshots**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/20668624/179145231-5ffcf09a-8c94-438f-a591-c5e5f6c479e7.png">

**OS (please complete the following information):**
 - MacOS Monterey v12.4

**Additional context**
N/A

**Comment by danvergara** [comment]
Thank you for bringing this to my attention.

I think this fairly easy to accomplish.

**Comment by danvergara** [comment]
@israteneda this bug has been addressed in #97. Feel free to take a look at it whenever you want.
